/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFrame;

import SingleTune.Tune;

/**
 *
 * @author shahriar
 */
//import SingleTune.Tune;
public class Equalizer extends javax.swing.JFrame{

    /**
     * Creates new form Equalizer
     */
    public void defaultValue(){
        /// setting default value
        dynamic_slider_value.setText("85"); 
        duration_slider_value.setText("90");
        pan_slider_value.setText("50");
        rythm_slider_value.setText("100");
    }
    
    public Equalizer() {
        initComponents();
        defaultValue();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        duration_slider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dynamic_slider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        pan_slider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        rythm_slider = new javax.swing.JSlider();
        duration_slider_value = new javax.swing.JLabel();
        rythm_slider_value = new javax.swing.JLabel();
        dynamic_slider_value = new javax.swing.JLabel();
        pan_slider_value = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        delay_slider = new javax.swing.JSlider();
        delay_slider_value = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        duration_slider.setBackground(new java.awt.Color(204, 255, 255));
        duration_slider.setMajorTickSpacing(20);
        duration_slider.setMaximum(170);
        duration_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        duration_slider.setPaintLabels(true);
        duration_slider.setPaintTicks(true);
        duration_slider.setValue(90);
        duration_slider.setRequestFocusEnabled(false);
        duration_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                duration_sliderStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Duration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Dynami");

        dynamic_slider.setBackground(new java.awt.Color(204, 255, 255));
        dynamic_slider.setMajorTickSpacing(20);
        dynamic_slider.setMaximum(127);
        dynamic_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        dynamic_slider.setPaintLabels(true);
        dynamic_slider.setPaintTicks(true);
        dynamic_slider.setValue(85);
        dynamic_slider.setRequestFocusEnabled(false);
        dynamic_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dynamic_sliderStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Pan");

        pan_slider.setBackground(new java.awt.Color(204, 255, 255));
        pan_slider.setMajorTickSpacing(20);
        pan_slider.setMaximum(170);
        pan_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        pan_slider.setPaintLabels(true);
        pan_slider.setPaintTicks(true);
        pan_slider.setRequestFocusEnabled(false);
        pan_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pan_sliderStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Rythm");

        rythm_slider.setBackground(new java.awt.Color(204, 255, 255));
        rythm_slider.setMajorTickSpacing(20);
        rythm_slider.setMaximum(170);
        rythm_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        rythm_slider.setPaintLabels(true);
        rythm_slider.setPaintTicks(true);
        rythm_slider.setValue(100);
        rythm_slider.setRequestFocusEnabled(false);
        rythm_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rythm_sliderStateChanged(evt);
            }
        });

        duration_slider_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rythm_slider_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dynamic_slider_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pan_slider_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Delay");

        delay_slider.setBackground(new java.awt.Color(204, 255, 255));
        delay_slider.setMajorTickSpacing(100);
        delay_slider.setMaximum(1000);
        delay_slider.setMinimum(200);
        delay_slider.setOrientation(javax.swing.JSlider.VERTICAL);
        delay_slider.setPaintLabels(true);
        delay_slider.setPaintTicks(true);
        delay_slider.setRequestFocusEnabled(false);
        delay_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                delay_sliderStateChanged(evt);
            }
        });

        delay_slider_value.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(dynamic_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pan_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pan_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rythm_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rythm_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delay_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delay_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(reset_btn)
                .addGap(128, 128, 128))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(714, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(dynamic_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(751, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reset_btn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(delay_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(delay_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(duration_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pan_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rythm_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dynamic_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(duration_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rythm_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pan_slider_value, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(306, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(dynamic_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Tune et = new Tune();
    private void dynamic_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dynamic_sliderStateChanged
        // TODO add your handling code here:
        
        // getting value from slider
        // setting it to dynamic(volume)
        // printing the value for bug test
        dynamic_slider_value.setText(Integer.toString(dynamic_slider.getValue()));
        et.setDynamic(dynamic_slider.getValue());
        System.out.println(dynamic_slider.getValue());
        System.out.println("get: "+et.getDynamic());
    }//GEN-LAST:event_dynamic_sliderStateChanged

    private void duration_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_duration_sliderStateChanged
        
        
        // getting value from duration slider 
        // set the value
        duration_slider_value.setText(Integer.toString(duration_slider.getValue()));
        double temp = duration_slider.getValue()/100;
        et.setDuration(temp);   
    }//GEN-LAST:event_duration_sliderStateChanged

    private void pan_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pan_sliderStateChanged
        
        // getting value from slider
        // set value
        pan_slider_value.setText(Integer.toString(pan_slider.getValue()));       
        double temp = pan_slider.getValue()/100;
        et.setPan(temp);
    }//GEN-LAST:event_pan_sliderStateChanged

    private void rythm_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rythm_sliderStateChanged
        
        
        // get rythm value
        // set rythm value
        rythm_slider_value.setText(Integer.toString(pan_slider.getValue()));
        double temp = rythm_slider.getValue()/100;
        et.setRythm(temp);
    }//GEN-LAST:event_rythm_sliderStateChanged

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        
        /// reset all the value to default
        /// these default value are given in jmusic library.
        
        dynamic_slider.setValue(85);
        duration_slider.setValue(90);
        pan_slider.setValue(50);
        rythm_slider.setValue(100);
    }//GEN-LAST:event_reset_btnActionPerformed

    private void delay_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_delay_sliderStateChanged
        
        // set the delay time.
        // this value is used in autoplay
        
        int temp = delay_slider.getValue();
        MyFrame.setDelay(temp);
        delay_slider_value.setText(Integer.toString(temp));
        
    }//GEN-LAST:event_delay_sliderStateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider delay_slider;
    private javax.swing.JLabel delay_slider_value;
    private javax.swing.JSlider duration_slider;
    private javax.swing.JLabel duration_slider_value;
    private javax.swing.JSlider dynamic_slider;
    private javax.swing.JLabel dynamic_slider_value;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider pan_slider;
    private javax.swing.JLabel pan_slider_value;
    private javax.swing.JButton reset_btn;
    private javax.swing.JSlider rythm_slider;
    private javax.swing.JLabel rythm_slider_value;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        new Equalizer().setVisible(true);
        
    }
}
