/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFrame;

import javax.swing.JFrame;
import SingleTune.Tune;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author home
 */
public class Frame_37 extends javax.swing.JFrame implements KeyListener{

    public Frame_37() {
        initComponents();
        jTextField1.addKeyListener(this);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
    }
    
    // creating object of tune class
    // tune class has all the node information to play
    Tune tone= new Tune();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        _37_s8_C3S = new javax.swing.JButton();
        _37_8_C3 = new javax.swing.JButton();
        _37_s9_D3S = new javax.swing.JButton();
        _37_0_E3 = new javax.swing.JButton();
        _37_9_D3 = new javax.swing.JButton();
        _37_sQ_F3S = new javax.swing.JButton();
        _37_Q_F3 = new javax.swing.JButton();
        _37_sW_G3S = new javax.swing.JButton();
        _37_W_G3 = new javax.swing.JButton();
        _37_sE_A3S = new javax.swing.JButton();
        _37_R_B3 = new javax.swing.JButton();
        _37_E_A3 = new javax.swing.JButton();
        _37_sT_C4S = new javax.swing.JButton();
        _37_T_C4 = new javax.swing.JButton();
        _37_sY_D4S = new javax.swing.JButton();
        _37_U_E4 = new javax.swing.JButton();
        _37_Y_D4 = new javax.swing.JButton();
        _37_sI_F4S = new javax.swing.JButton();
        _37_I_F4 = new javax.swing.JButton();
        _37_sO_G4S = new javax.swing.JButton();
        _37_O_G4 = new javax.swing.JButton();
        _37_sP_A4S = new javax.swing.JButton();
        _37_A_B4 = new javax.swing.JButton();
        _37_P_A4 = new javax.swing.JButton();
        _37_sS_C5S = new javax.swing.JButton();
        _37_S_C5 = new javax.swing.JButton();
        _37_sD_D5S = new javax.swing.JButton();
        _37_F_E5 = new javax.swing.JButton();
        _37_D_D5 = new javax.swing.JButton();
        _37_sG_F5S = new javax.swing.JButton();
        _37_G_F5 = new javax.swing.JButton();
        _37_sH_G5S = new javax.swing.JButton();
        _37_H_G5 = new javax.swing.JButton();
        _37_sJ_A5S = new javax.swing.JButton();
        _37_K_C6 = new javax.swing.JButton();
        _37_J_A5 = new javax.swing.JButton();
        _37_K_B6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        _37_s8_C3S.setBackground(new java.awt.Color(0, 0, 0));
        _37_s8_C3S.setText("jButton2");
        _37_s8_C3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_s8_C3SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_s8_C3S);
        _37_s8_C3S.setBounds(172, 150, 30, 140);

        _37_8_C3.setText("8");
        _37_8_C3.setToolTipText("");
        _37_8_C3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_8_C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_8_C3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_8_C3);
        _37_8_C3.setBounds(140, 150, 47, 261);

        _37_s9_D3S.setBackground(new java.awt.Color(0, 0, 0));
        _37_s9_D3S.setText("jButton2");
        _37_s9_D3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_s9_D3SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_s9_D3S);
        _37_s9_D3S.setBounds(218, 150, 30, 140);

        _37_0_E3.setText("0");
        _37_0_E3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_0_E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_0_E3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_0_E3);
        _37_0_E3.setBounds(232, 150, 47, 261);

        _37_9_D3.setText("9");
        _37_9_D3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_9_D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_9_D3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_9_D3);
        _37_9_D3.setBounds(186, 150, 47, 261);

        _37_sQ_F3S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sQ_F3S.setText("jButton2");
        _37_sQ_F3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sQ_F3SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sQ_F3S);
        _37_sQ_F3S.setBounds(311, 150, 30, 140);

        _37_Q_F3.setText("Q");
        _37_Q_F3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_Q_F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_Q_F3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_Q_F3);
        _37_Q_F3.setBounds(278, 150, 47, 261);

        _37_sW_G3S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sW_G3S.setText("jButton2");
        _37_sW_G3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sW_G3SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sW_G3S);
        _37_sW_G3S.setBounds(357, 150, 30, 140);

        _37_W_G3.setText("W");
        _37_W_G3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_W_G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_W_G3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_W_G3);
        _37_W_G3.setBounds(324, 150, 47, 261);

        _37_sE_A3S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sE_A3S.setText("jButton2");
        _37_sE_A3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sE_A3SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sE_A3S);
        _37_sE_A3S.setBounds(402, 150, 30, 140);

        _37_R_B3.setText("R");
        _37_R_B3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_R_B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_R_B3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_R_B3);
        _37_R_B3.setBounds(416, 150, 47, 261);

        _37_E_A3.setText("E");
        _37_E_A3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_E_A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_E_A3ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_E_A3);
        _37_E_A3.setBounds(370, 150, 47, 261);

        _37_sT_C4S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sT_C4S.setText("jButton2");
        _37_sT_C4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sT_C4SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sT_C4S);
        _37_sT_C4S.setBounds(494, 150, 30, 140);

        _37_T_C4.setText("T");
        _37_T_C4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_T_C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_T_C4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_T_C4);
        _37_T_C4.setBounds(462, 150, 47, 261);

        _37_sY_D4S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sY_D4S.setText("jButton2");
        _37_sY_D4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sY_D4SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sY_D4S);
        _37_sY_D4S.setBounds(541, 150, 30, 140);

        _37_U_E4.setText("U");
        _37_U_E4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_U_E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_U_E4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_U_E4);
        _37_U_E4.setBounds(554, 150, 47, 261);

        _37_Y_D4.setText("Y");
        _37_Y_D4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_Y_D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_Y_D4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_Y_D4);
        _37_Y_D4.setBounds(508, 150, 47, 261);

        _37_sI_F4S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sI_F4S.setText("jButton2");
        _37_sI_F4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sI_F4SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sI_F4S);
        _37_sI_F4S.setBounds(632, 150, 30, 140);

        _37_I_F4.setText("I");
        _37_I_F4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_I_F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_I_F4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_I_F4);
        _37_I_F4.setBounds(600, 150, 47, 261);

        _37_sO_G4S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sO_G4S.setText("jButton2");
        _37_sO_G4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sO_G4SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sO_G4S);
        _37_sO_G4S.setBounds(678, 150, 30, 140);

        _37_O_G4.setText("O");
        _37_O_G4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_O_G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_O_G4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_O_G4);
        _37_O_G4.setBounds(646, 150, 47, 261);

        _37_sP_A4S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sP_A4S.setText("jButton2");
        _37_sP_A4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sP_A4SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sP_A4S);
        _37_sP_A4S.setBounds(725, 150, 30, 140);

        _37_A_B4.setText("A");
        _37_A_B4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_A_B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_A_B4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_A_B4);
        _37_A_B4.setBounds(738, 150, 47, 261);

        _37_P_A4.setText("P");
        _37_P_A4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_P_A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_P_A4ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_P_A4);
        _37_P_A4.setBounds(692, 150, 47, 261);

        _37_sS_C5S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sS_C5S.setText("jButton2");
        _37_sS_C5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sS_C5SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sS_C5S);
        _37_sS_C5S.setBounds(816, 150, 30, 140);

        _37_S_C5.setText("S");
        _37_S_C5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_S_C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_S_C5ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_S_C5);
        _37_S_C5.setBounds(784, 150, 47, 261);

        _37_sD_D5S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sD_D5S.setText("jButton2");
        _37_sD_D5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sD_D5SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sD_D5S);
        _37_sD_D5S.setBounds(862, 150, 30, 140);

        _37_F_E5.setText("F");
        _37_F_E5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_F_E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_F_E5ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_F_E5);
        _37_F_E5.setBounds(876, 150, 47, 261);

        _37_D_D5.setText("D");
        _37_D_D5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_D_D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_D_D5ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_D_D5);
        _37_D_D5.setBounds(830, 150, 47, 261);

        _37_sG_F5S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sG_F5S.setText("jButton2");
        _37_sG_F5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sG_F5SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sG_F5S);
        _37_sG_F5S.setBounds(954, 150, 30, 140);

        _37_G_F5.setText("G");
        _37_G_F5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_G_F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_G_F5ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_G_F5);
        _37_G_F5.setBounds(922, 150, 47, 261);

        _37_sH_G5S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sH_G5S.setText("jButton2");
        _37_sH_G5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sH_G5SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sH_G5S);
        _37_sH_G5S.setBounds(1000, 150, 30, 140);

        _37_H_G5.setText("H");
        _37_H_G5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_H_G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_H_G5ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_H_G5);
        _37_H_G5.setBounds(968, 150, 47, 261);

        _37_sJ_A5S.setBackground(new java.awt.Color(0, 0, 0));
        _37_sJ_A5S.setText("jButton2");
        _37_sJ_A5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_sJ_A5SActionPerformed(evt);
            }
        });
        jPanel1.add(_37_sJ_A5S);
        _37_sJ_A5S.setBounds(1047, 150, 30, 140);

        _37_K_C6.setText("L");
        _37_K_C6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_K_C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_K_C6ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_K_C6);
        _37_K_C6.setBounds(1106, 150, 47, 261);

        _37_J_A5.setText("J");
        _37_J_A5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_J_A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_J_A5ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_J_A5);
        _37_J_A5.setBounds(1014, 150, 47, 261);

        _37_K_B6.setText("K");
        _37_K_B6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _37_K_B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _37_K_B6ActionPerformed(evt);
            }
        });
        jPanel1.add(_37_K_B6);
        _37_K_B6.setBounds(1060, 150, 47, 261);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1040, 470, 55, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(400, 460, 330, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _37_sW_G3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sW_G3SActionPerformed
        
        tone.tf_ws_G3s();
    }//GEN-LAST:event__37_sW_G3SActionPerformed

    private void _37_sE_A3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sE_A3SActionPerformed
        // TODO add your handling code here:
        tone.tf_es_A3s();
    }//GEN-LAST:event__37_sE_A3SActionPerformed

    private void _37_sO_G4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sO_G4SActionPerformed
        // TODO add your handling code here:
        tone.tf_os_G4s();
    }//GEN-LAST:event__37_sO_G4SActionPerformed

    private void _37_sP_A4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sP_A4SActionPerformed
        // TODO add your handling code here:
        tone.tf_ps_A4s();
    }//GEN-LAST:event__37_sP_A4SActionPerformed

    private void _37_sH_G5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sH_G5SActionPerformed
        // TODO add your handling code here:
        tone.tf_hs_G5s();
    }//GEN-LAST:event__37_sH_G5SActionPerformed

    private void _37_sJ_A5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sJ_A5SActionPerformed
        // TODO add your handling code here:
        tone.tf_js_A5s();
    }//GEN-LAST:event__37_sJ_A5SActionPerformed

    private void _37_U_E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_U_E4ActionPerformed
        // TODO add your handling code here:
        tone.tf_u_E4();
    }//GEN-LAST:event__37_U_E4ActionPerformed

    private void _37_8_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_8_C3ActionPerformed
        // TODO add your handling code here:
        tone.tf_8_C3();
    }//GEN-LAST:event__37_8_C3ActionPerformed

    private void _37_9_D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_9_D3ActionPerformed
        // TODO add your handling code here:
        tone.tf_9_D3();
    }//GEN-LAST:event__37_9_D3ActionPerformed

    private void _37_0_E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_0_E3ActionPerformed
        // TODO add your handling code here:
        tone.tf_0_E3();
    }//GEN-LAST:event__37_0_E3ActionPerformed

    private void _37_Q_F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_Q_F3ActionPerformed
        // TODO add your handling code here:
        tone.tf_q_F3();
    }//GEN-LAST:event__37_Q_F3ActionPerformed

    private void _37_W_G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_W_G3ActionPerformed
        // TODO add your handling code here:
        tone.tf_w_G3();
    }//GEN-LAST:event__37_W_G3ActionPerformed

    private void _37_E_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_E_A3ActionPerformed
        // TODO add your handling code here:
        tone.tf_e_A3();
    }//GEN-LAST:event__37_E_A3ActionPerformed

    private void _37_R_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_R_B3ActionPerformed
        // TODO add your handling code here:
        tone.tf_r_B3();
    }//GEN-LAST:event__37_R_B3ActionPerformed

    private void _37_T_C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_T_C4ActionPerformed
        // TODO add your handling code here:
        tone.tf_t_C4();
    }//GEN-LAST:event__37_T_C4ActionPerformed

    private void _37_Y_D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_Y_D4ActionPerformed
        // TODO add your handling code here:
        tone.tf_y_D4();
    }//GEN-LAST:event__37_Y_D4ActionPerformed

    private void _37_I_F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_I_F4ActionPerformed
        // TODO add your handling code here:
        tone.tf_i_F4();
    }//GEN-LAST:event__37_I_F4ActionPerformed

    private void _37_O_G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_O_G4ActionPerformed
        // TODO add your handling code here:
        tone.tf_o_G4();
    }//GEN-LAST:event__37_O_G4ActionPerformed

    private void _37_P_A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_P_A4ActionPerformed
        // TODO add your handling code here:
        tone.tf_p_A4();
    }//GEN-LAST:event__37_P_A4ActionPerformed

    private void _37_A_B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_A_B4ActionPerformed
        // TODO add your handling code here:
         tone.tf_a_B4();
    }//GEN-LAST:event__37_A_B4ActionPerformed

    private void _37_S_C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_S_C5ActionPerformed
        // TODO add your handling code here:
        tone.tf_s_C5();
    }//GEN-LAST:event__37_S_C5ActionPerformed

    private void _37_D_D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_D_D5ActionPerformed
        // TODO add your handling code here:
        tone.tf_d_D5();
    }//GEN-LAST:event__37_D_D5ActionPerformed

    private void _37_F_E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_F_E5ActionPerformed
        // TODO add your handling code here:
         tone.tf_f_E5();
    }//GEN-LAST:event__37_F_E5ActionPerformed

    private void _37_G_F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_G_F5ActionPerformed
        // TODO add your handling code here:
          tone.tf_g_F5();

    }//GEN-LAST:event__37_G_F5ActionPerformed

    private void _37_H_G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_H_G5ActionPerformed
        // TODO add your handling code here:
          tone.tf_h_G5();
    }//GEN-LAST:event__37_H_G5ActionPerformed

    private void _37_J_A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_J_A5ActionPerformed
        // TODO add your handling code here:
        tone.tf_j_A5();
    }//GEN-LAST:event__37_J_A5ActionPerformed

    private void _37_K_B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_K_B6ActionPerformed
        // TODO add your handling code here:
        tone.tf_k_B5();
    }//GEN-LAST:event__37_K_B6ActionPerformed

    private void _37_K_C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_K_C6ActionPerformed
        // TODO add your handling code here:
         tone.tf_l_C6();
    }//GEN-LAST:event__37_K_C6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MyFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void _37_s8_C3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_s8_C3SActionPerformed
        // TODO add your handling code here
        tone.tf_8s_C3s();
    }//GEN-LAST:event__37_s8_C3SActionPerformed

    private void _37_s9_D3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_s9_D3SActionPerformed
        // TODO add your handling code here:
        tone.tf_9s_D3s();
    }//GEN-LAST:event__37_s9_D3SActionPerformed

    private void _37_sQ_F3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sQ_F3SActionPerformed
        // TODO add your handling code here:
        tone.tf_qs_F3s();
    }//GEN-LAST:event__37_sQ_F3SActionPerformed

    private void _37_sT_C4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sT_C4SActionPerformed
        // TODO add your handling code here:
        tone.tf_ts_C4s();
    }//GEN-LAST:event__37_sT_C4SActionPerformed

    private void _37_sY_D4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sY_D4SActionPerformed
        // TODO add your handling code here:
        tone.tf_ys_D4s();
    }//GEN-LAST:event__37_sY_D4SActionPerformed

    private void _37_sI_F4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sI_F4SActionPerformed
        // TODO add your handling code here:
        tone.tf_is_F4s();
    }//GEN-LAST:event__37_sI_F4SActionPerformed

    private void _37_sS_C5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sS_C5SActionPerformed
        // TODO add your handling code here:
        tone.tf_ss_C5s();
    }//GEN-LAST:event__37_sS_C5SActionPerformed

    private void _37_sD_D5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sD_D5SActionPerformed
        // TODO add your handling code here:
        tone.tf_ds_D5s();
    }//GEN-LAST:event__37_sD_D5SActionPerformed

    private void _37_sG_F5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__37_sG_F5SActionPerformed
        // TODO add your handling code here:
        tone.tf_gs_F5s();
    }//GEN-LAST:event__37_sG_F5SActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_37.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_37.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_37.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_37.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_37().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _37_0_E3;
    private javax.swing.JButton _37_8_C3;
    private javax.swing.JButton _37_9_D3;
    private javax.swing.JButton _37_A_B4;
    private javax.swing.JButton _37_D_D5;
    private javax.swing.JButton _37_E_A3;
    private javax.swing.JButton _37_F_E5;
    private javax.swing.JButton _37_G_F5;
    private javax.swing.JButton _37_H_G5;
    private javax.swing.JButton _37_I_F4;
    private javax.swing.JButton _37_J_A5;
    private javax.swing.JButton _37_K_B6;
    private javax.swing.JButton _37_K_C6;
    private javax.swing.JButton _37_O_G4;
    private javax.swing.JButton _37_P_A4;
    private javax.swing.JButton _37_Q_F3;
    private javax.swing.JButton _37_R_B3;
    private javax.swing.JButton _37_S_C5;
    private javax.swing.JButton _37_T_C4;
    private javax.swing.JButton _37_U_E4;
    private javax.swing.JButton _37_W_G3;
    private javax.swing.JButton _37_Y_D4;
    private javax.swing.JButton _37_s8_C3S;
    private javax.swing.JButton _37_s9_D3S;
    private javax.swing.JButton _37_sD_D5S;
    private javax.swing.JButton _37_sE_A3S;
    private javax.swing.JButton _37_sG_F5S;
    private javax.swing.JButton _37_sH_G5S;
    private javax.swing.JButton _37_sI_F4S;
    private javax.swing.JButton _37_sJ_A5S;
    private javax.swing.JButton _37_sO_G4S;
    private javax.swing.JButton _37_sP_A4S;
    private javax.swing.JButton _37_sQ_F3S;
    private javax.swing.JButton _37_sS_C5S;
    private javax.swing.JButton _37_sT_C4S;
    private javax.swing.JButton _37_sW_G3S;
    private javax.swing.JButton _37_sY_D4S;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if(e.getKeyCode() == KeyEvent.VK_0){
            tone.tf_0_E3();
        }
        if(e.getKeyCode() == KeyEvent.VK_8){
            tone.tf_8_C3();
        }
        if(e.getKeyCode() == KeyEvent.VK_9){
            tone.tf_9_D3();
        }
        if(e.getKeyCode() == KeyEvent.VK_Q){
            tone.tf_q_F3();
        }
        if(e.getKeyCode() == KeyEvent.VK_W){
            tone.tf_w_G3();
        }
        if(e.getKeyCode() == KeyEvent.VK_E){
            tone.tf_e_A3();
        }
        if(e.getKeyCode() == KeyEvent.VK_R){
            tone.tf_r_B3();
        }
        if(e.getKeyCode() == KeyEvent.VK_T){
            tone.tf_t_C4();
        }
        if(e.getKeyCode() == KeyEvent.VK_Y){
            tone.tf_y_D4();
        }
        if(e.getKeyCode() == KeyEvent.VK_U){
            tone.tf_u_E4();
        }
        if(e.getKeyCode() == KeyEvent.VK_I){
            tone.tf_i_F4();
        }
        if(e.getKeyCode() == KeyEvent.VK_O){
            tone.tf_o_G4();
        }
        if(e.getKeyCode() == KeyEvent.VK_P){
            tone.tf_p_A4();
        }
        if(e.getKeyCode() == KeyEvent.VK_A){
            tone.tf_a_B4();
        }
        if(e.getKeyCode() == KeyEvent.VK_S){
            tone.tf_s_C5();
        }
        if(e.getKeyCode() == KeyEvent.VK_D){
            tone.tf_d_D5();
        }
        if(e.getKeyCode() == KeyEvent.VK_F){
            tone.tf_f_E5();
        }
        if(e.getKeyCode() == KeyEvent.VK_G){
            tone.tf_g_F5();
        }
        if(e.getKeyCode() == KeyEvent.VK_H){
            tone.tf_h_G5();
        }
        if(e.getKeyCode() == KeyEvent.VK_J){
            tone.tf_j_A5();
        }
        if(e.getKeyCode() == KeyEvent.VK_K){
            tone.tf_k_B5();
        }
        if(e.getKeyCode() == KeyEvent.VK_L){
            tone.tf_l_C6();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    
}
