/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFrame;
import SingleTune.Tune;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.TargetDataLine;
import javax.swing.JFileChooser;
import javazoom.jl.player.Player;
import jm.JMC;
import jm.music.data.Note;
import jm.util.Play;
import rsbutton.RSButtonMetro;

/**
 *
 * @author shahriar
 */
public class MyFrame extends javax.swing.JFrame implements KeyListener{
    
    public MyFrame() {
        initComponents();
        keyInput.addKeyListener(this);
    }
    
    
    /// Creating Object of Tune class.
    /// Tune class has all the property for playing a tune.
    Tune tone= new Tune();
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_61_piano_ = new rsbutton.RSButtonMetro();
        btn_37_piano_ = new rsbutton.RSButtonMetro();
        btn_equalizer_ = new rsbutton.RSButtonMetro();
        pianoPanel = new javax.swing.JPanel();
        _s1_C2S = new javax.swing.JButton();
        _s2_D2S = new javax.swing.JButton();
        _s4_F2S = new javax.swing.JButton();
        _s5_G2S = new javax.swing.JButton();
        _s6_A2S = new javax.swing.JButton();
        _s8_C3S = new javax.swing.JButton();
        _s9_D3S = new javax.swing.JButton();
        _sQ_F3S = new javax.swing.JButton();
        _sW_G3S = new javax.swing.JButton();
        _sE_A3S = new javax.swing.JButton();
        _sT_C4S = new javax.swing.JButton();
        _sY_D4S = new javax.swing.JButton();
        _sI_F4S = new javax.swing.JButton();
        _sO_G4S = new javax.swing.JButton();
        _sP_A4S = new javax.swing.JButton();
        _sS_C5S = new javax.swing.JButton();
        _sD_D5S = new javax.swing.JButton();
        _sG_F5S = new javax.swing.JButton();
        _sH_G5S = new javax.swing.JButton();
        _sJ_A5S = new javax.swing.JButton();
        _sL_C6S = new javax.swing.JButton();
        _sZ_D6S = new javax.swing.JButton();
        _sC_F6S = new javax.swing.JButton();
        _sV_G6S = new javax.swing.JButton();
        _sB_A6S = new javax.swing.JButton();
        _1_C2 = new javax.swing.JButton();
        _2_D2 = new javax.swing.JButton();
        _3_E2 = new javax.swing.JButton();
        _4_F2 = new javax.swing.JButton();
        _5_G2 = new javax.swing.JButton();
        _6_A2 = new javax.swing.JButton();
        _7_B2 = new javax.swing.JButton();
        _8_C3 = new javax.swing.JButton();
        _9_D3 = new javax.swing.JButton();
        _0_E3 = new javax.swing.JButton();
        _Q_F3 = new javax.swing.JButton();
        _W_G3 = new javax.swing.JButton();
        _E_A3 = new javax.swing.JButton();
        _R_B3 = new javax.swing.JButton();
        _T_C4 = new javax.swing.JButton();
        _Y_D4 = new javax.swing.JButton();
        _U_E4 = new javax.swing.JButton();
        _I_F4 = new javax.swing.JButton();
        _O_G4 = new javax.swing.JButton();
        _P_A4 = new javax.swing.JButton();
        _A_B4 = new javax.swing.JButton();
        _S_C5 = new javax.swing.JButton();
        _D_D5 = new javax.swing.JButton();
        _F_E5 = new javax.swing.JButton();
        _G_F5 = new javax.swing.JButton();
        _H_G5 = new javax.swing.JButton();
        _J_A5 = new javax.swing.JButton();
        _K_B5 = new javax.swing.JButton();
        _L_C6 = new javax.swing.JButton();
        _Z_D6 = new javax.swing.JButton();
        _X_E6 = new javax.swing.JButton();
        _C_F6 = new javax.swing.JButton();
        _V_G6 = new javax.swing.JButton();
        _B_A6 = new javax.swing.JButton();
        _N_B6 = new javax.swing.JButton();
        _M_C7 = new javax.swing.JButton();
        keyInput = new javax.swing.JTextField();
        playTuneInput = new rsbutton.RSButtonMetro();
        pianoBGImane = new javax.swing.JLabel();
        topmenu = new javax.swing.JPanel();
        btn_side_menu_slider_ = new javax.swing.JButton();
        btn_pause_music = new rsbutton.RSButtonMetro();
        btn_play_music = new rsbutton.RSButtonMetro();
        btn_stop_record = new rsbutton.RSButtonMetro();
        btn_stop_music = new rsbutton.RSButtonMetro();
        btn_start_record = new rsbutton.RSButtonMetro();
        lbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        save_name_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        sideMenu.setBackground(new java.awt.Color(0, 204, 204));
        sideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PIANOS");
        sideMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 50));

        btn_61_piano_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-piano-40.png"))); // NOI18N
        btn_61_piano_.setText("61 PIANO");
        btn_61_piano_.setColorHover(new java.awt.Color(204, 204, 204));
        btn_61_piano_.setColorNormal(new java.awt.Color(214, 217, 223));
        btn_61_piano_.setColorPressed(new java.awt.Color(214, 217, 223));
        btn_61_piano_.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn_61_piano_.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn_61_piano_.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn_61_piano_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_61_piano_.setIconTextGap(5);
        sideMenu.add(btn_61_piano_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 50));

        btn_37_piano_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-piano-40.png"))); // NOI18N
        btn_37_piano_.setText("37 PIANO");
        btn_37_piano_.setColorHover(new java.awt.Color(204, 204, 204));
        btn_37_piano_.setColorNormal(new java.awt.Color(214, 217, 223));
        btn_37_piano_.setColorPressed(new java.awt.Color(214, 217, 223));
        btn_37_piano_.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn_37_piano_.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn_37_piano_.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn_37_piano_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_37_piano_.setIconTextGap(5);
        btn_37_piano_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_37_piano_ActionPerformed(evt);
            }
        });
        sideMenu.add(btn_37_piano_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, 50));

        btn_equalizer_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-tune-40.png"))); // NOI18N
        btn_equalizer_.setText("EQUALIZER");
        btn_equalizer_.setColorHover(new java.awt.Color(204, 204, 204));
        btn_equalizer_.setColorNormal(new java.awt.Color(74, 80, 82));
        btn_equalizer_.setColorPressed(new java.awt.Color(214, 217, 223));
        btn_equalizer_.setColorTextHover(new java.awt.Color(128, 128, 131));
        btn_equalizer_.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btn_equalizer_.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btn_equalizer_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_equalizer_.setIconTextGap(5);
        btn_equalizer_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equalizer_ActionPerformed(evt);
            }
        });
        sideMenu.add(btn_equalizer_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 211, 140, 50));

        pianoPanel.setBackground(new java.awt.Color(0, 51, 51));
        pianoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pianoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        _s1_C2S.setBackground(new java.awt.Color(0, 0, 0));
        _s1_C2S.setBorder(null);
        _s1_C2S.setFocusPainted(false);
        _s1_C2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s1_C2SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s1_C2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 166, 24, 140));

        _s2_D2S.setBackground(new java.awt.Color(0, 0, 0));
        _s2_D2S.setBorder(null);
        _s2_D2S.setFocusPainted(false);
        _s2_D2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s2_D2SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s2_D2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 166, 24, 140));

        _s4_F2S.setBackground(new java.awt.Color(0, 0, 0));
        _s4_F2S.setBorder(null);
        _s4_F2S.setFocusPainted(false);
        _s4_F2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s4_F2SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s4_F2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 166, 24, 140));

        _s5_G2S.setBackground(new java.awt.Color(0, 0, 0));
        _s5_G2S.setBorder(null);
        _s5_G2S.setFocusPainted(false);
        _s5_G2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s5_G2SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s5_G2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 166, 24, 140));

        _s6_A2S.setBackground(new java.awt.Color(0, 0, 0));
        _s6_A2S.setBorder(null);
        _s6_A2S.setFocusPainted(false);
        _s6_A2S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s6_A2SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s6_A2S, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 166, 24, 140));

        _s8_C3S.setBackground(new java.awt.Color(0, 0, 0));
        _s8_C3S.setBorder(null);
        _s8_C3S.setFocusPainted(false);
        _s8_C3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s8_C3SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s8_C3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 166, 24, 140));

        _s9_D3S.setBackground(new java.awt.Color(0, 0, 0));
        _s9_D3S.setBorder(null);
        _s9_D3S.setFocusPainted(false);
        _s9_D3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _s9_D3SActionPerformed(evt);
            }
        });
        pianoPanel.add(_s9_D3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 166, 24, 140));

        _sQ_F3S.setBackground(new java.awt.Color(0, 0, 0));
        _sQ_F3S.setBorder(null);
        _sQ_F3S.setFocusPainted(false);
        _sQ_F3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sQ_F3SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sQ_F3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 166, 24, 140));

        _sW_G3S.setBackground(new java.awt.Color(0, 0, 0));
        _sW_G3S.setBorder(null);
        _sW_G3S.setFocusPainted(false);
        _sW_G3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sW_G3SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sW_G3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 166, 24, 140));

        _sE_A3S.setBackground(new java.awt.Color(0, 0, 0));
        _sE_A3S.setBorder(null);
        _sE_A3S.setFocusPainted(false);
        _sE_A3S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sE_A3SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sE_A3S, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 166, 24, 140));

        _sT_C4S.setBackground(new java.awt.Color(0, 0, 0));
        _sT_C4S.setBorder(null);
        _sT_C4S.setFocusPainted(false);
        _sT_C4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sT_C4SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sT_C4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 166, 24, 140));

        _sY_D4S.setBackground(new java.awt.Color(0, 0, 0));
        _sY_D4S.setBorder(null);
        _sY_D4S.setFocusPainted(false);
        _sY_D4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sY_D4SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sY_D4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 166, 24, 140));

        _sI_F4S.setBackground(new java.awt.Color(0, 0, 0));
        _sI_F4S.setBorder(null);
        _sI_F4S.setFocusPainted(false);
        _sI_F4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sI_F4SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sI_F4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 166, 24, 140));

        _sO_G4S.setBackground(new java.awt.Color(0, 0, 0));
        _sO_G4S.setBorder(null);
        _sO_G4S.setFocusPainted(false);
        _sO_G4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sO_G4SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sO_G4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 166, 24, 140));

        _sP_A4S.setBackground(new java.awt.Color(0, 0, 0));
        _sP_A4S.setBorder(null);
        _sP_A4S.setFocusPainted(false);
        _sP_A4S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sP_A4SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sP_A4S, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 166, 24, 140));

        _sS_C5S.setBackground(new java.awt.Color(0, 0, 0));
        _sS_C5S.setBorder(null);
        _sS_C5S.setFocusPainted(false);
        _sS_C5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sS_C5SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sS_C5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 166, 24, 140));

        _sD_D5S.setBackground(new java.awt.Color(0, 0, 0));
        _sD_D5S.setBorder(null);
        _sD_D5S.setFocusPainted(false);
        _sD_D5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sD_D5SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sD_D5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 166, 24, 140));

        _sG_F5S.setBackground(new java.awt.Color(0, 0, 0));
        _sG_F5S.setBorder(null);
        _sG_F5S.setFocusPainted(false);
        _sG_F5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sG_F5SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sG_F5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 166, 24, 140));

        _sH_G5S.setBackground(new java.awt.Color(0, 0, 0));
        _sH_G5S.setBorder(null);
        _sH_G5S.setFocusPainted(false);
        _sH_G5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sH_G5SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sH_G5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 166, 24, 140));

        _sJ_A5S.setBackground(new java.awt.Color(0, 0, 0));
        _sJ_A5S.setBorder(null);
        _sJ_A5S.setFocusPainted(false);
        _sJ_A5S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sJ_A5SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sJ_A5S, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 166, 24, 140));

        _sL_C6S.setBackground(new java.awt.Color(0, 0, 0));
        _sL_C6S.setBorder(null);
        _sL_C6S.setFocusPainted(false);
        _sL_C6S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sL_C6SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sL_C6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 166, 24, 140));

        _sZ_D6S.setBackground(new java.awt.Color(0, 0, 0));
        _sZ_D6S.setBorder(null);
        _sZ_D6S.setFocusPainted(false);
        _sZ_D6S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sZ_D6SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sZ_D6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 166, 24, 140));

        _sC_F6S.setBackground(new java.awt.Color(0, 0, 0));
        _sC_F6S.setBorder(null);
        _sC_F6S.setFocusPainted(false);
        _sC_F6S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sC_F6SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sC_F6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 166, 24, 140));

        _sV_G6S.setBackground(new java.awt.Color(0, 0, 0));
        _sV_G6S.setBorder(null);
        _sV_G6S.setFocusPainted(false);
        _sV_G6S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sV_G6SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sV_G6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(1126, 166, 24, 140));

        _sB_A6S.setBackground(new java.awt.Color(0, 0, 0));
        _sB_A6S.setBorder(null);
        _sB_A6S.setFocusPainted(false);
        _sB_A6S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _sB_A6SActionPerformed(evt);
            }
        });
        pianoPanel.add(_sB_A6S, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 166, 24, 140));

        _1_C2.setText("1");
        _1_C2.setBorder(null);
        _1_C2.setFocusPainted(false);
        _1_C2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _1_C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1_C2ActionPerformed(evt);
            }
        });
        _1_C2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _1_C2KeyPressed(evt);
            }
        });
        pianoPanel.add(_1_C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 166, 36, 215));

        _2_D2.setText("2");
        _2_D2.setBorder(null);
        _2_D2.setFocusPainted(false);
        _2_D2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _2_D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2_D2ActionPerformed(evt);
            }
        });
        pianoPanel.add(_2_D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 166, 36, 215));

        _3_E2.setText("3");
        _3_E2.setBorder(null);
        _3_E2.setFocusPainted(false);
        _3_E2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _3_E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3_E2ActionPerformed(evt);
            }
        });
        pianoPanel.add(_3_E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 166, 36, 215));

        _4_F2.setText("4");
        _4_F2.setBorder(null);
        _4_F2.setFocusPainted(false);
        _4_F2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _4_F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4_F2ActionPerformed(evt);
            }
        });
        pianoPanel.add(_4_F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 166, 36, 215));

        _5_G2.setText("5");
        _5_G2.setBorder(null);
        _5_G2.setFocusPainted(false);
        _5_G2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _5_G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5_G2ActionPerformed(evt);
            }
        });
        pianoPanel.add(_5_G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 166, 36, 215));

        _6_A2.setText("6");
        _6_A2.setBorder(null);
        _6_A2.setFocusPainted(false);
        _6_A2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _6_A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _6_A2ActionPerformed(evt);
            }
        });
        pianoPanel.add(_6_A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 166, 36, 215));

        _7_B2.setText("7");
        _7_B2.setBorder(null);
        _7_B2.setFocusPainted(false);
        _7_B2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _7_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _7_B2ActionPerformed(evt);
            }
        });
        pianoPanel.add(_7_B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 166, 36, 215));

        _8_C3.setText("8");
        _8_C3.setBorder(null);
        _8_C3.setFocusPainted(false);
        _8_C3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _8_C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _8_C3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_8_C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 166, 36, 215));

        _9_D3.setText("9");
        _9_D3.setBorder(null);
        _9_D3.setFocusPainted(false);
        _9_D3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _9_D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _9_D3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_9_D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 166, 36, 215));

        _0_E3.setText("0");
        _0_E3.setBorder(null);
        _0_E3.setFocusPainted(false);
        _0_E3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _0_E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _0_E3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_0_E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 166, 36, 215));

        _Q_F3.setText("Q");
        _Q_F3.setBorder(null);
        _Q_F3.setFocusPainted(false);
        _Q_F3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _Q_F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Q_F3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_Q_F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 166, 36, 215));

        _W_G3.setText("W");
        _W_G3.setBorder(null);
        _W_G3.setFocusPainted(false);
        _W_G3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _W_G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _W_G3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_W_G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 166, 36, 215));

        _E_A3.setText("E");
        _E_A3.setBorder(null);
        _E_A3.setFocusPainted(false);
        _E_A3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _E_A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _E_A3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_E_A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 166, 36, 215));

        _R_B3.setText("R");
        _R_B3.setBorder(null);
        _R_B3.setFocusPainted(false);
        _R_B3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _R_B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _R_B3ActionPerformed(evt);
            }
        });
        pianoPanel.add(_R_B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 166, 36, 215));

        _T_C4.setText("T");
        _T_C4.setBorder(null);
        _T_C4.setFocusPainted(false);
        _T_C4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _T_C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _T_C4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_T_C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 166, 36, 215));

        _Y_D4.setText("Y");
        _Y_D4.setBorder(null);
        _Y_D4.setFocusPainted(false);
        _Y_D4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _Y_D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Y_D4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_Y_D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 166, 36, 215));

        _U_E4.setText("U");
        _U_E4.setBorder(null);
        _U_E4.setFocusPainted(false);
        _U_E4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _U_E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _U_E4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_U_E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 166, 36, 215));

        _I_F4.setText("I");
        _I_F4.setBorder(null);
        _I_F4.setFocusPainted(false);
        _I_F4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _I_F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _I_F4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_I_F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 166, 36, 215));

        _O_G4.setText("O");
        _O_G4.setBorder(null);
        _O_G4.setFocusPainted(false);
        _O_G4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _O_G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _O_G4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_O_G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 166, 36, 215));

        _P_A4.setText("P");
        _P_A4.setBorder(null);
        _P_A4.setFocusPainted(false);
        _P_A4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _P_A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _P_A4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_P_A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 166, 36, 215));

        _A_B4.setText("A");
        _A_B4.setBorder(null);
        _A_B4.setFocusPainted(false);
        _A_B4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _A_B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _A_B4ActionPerformed(evt);
            }
        });
        pianoPanel.add(_A_B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 166, 36, 215));

        _S_C5.setText("S");
        _S_C5.setBorder(null);
        _S_C5.setFocusPainted(false);
        _S_C5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _S_C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _S_C5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_S_C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 166, 36, 215));

        _D_D5.setText("D");
        _D_D5.setBorder(null);
        _D_D5.setFocusPainted(false);
        _D_D5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _D_D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _D_D5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_D_D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 166, 36, 215));

        _F_E5.setText("F");
        _F_E5.setBorder(null);
        _F_E5.setFocusPainted(false);
        _F_E5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _F_E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _F_E5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_F_E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 166, 36, 215));

        _G_F5.setText("G");
        _G_F5.setBorder(null);
        _G_F5.setFocusPainted(false);
        _G_F5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _G_F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _G_F5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_G_F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(831, 166, 36, 215));

        _H_G5.setText("H");
        _H_G5.setBorder(null);
        _H_G5.setFocusPainted(false);
        _H_G5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _H_G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _H_G5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_H_G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 166, 36, 215));

        _J_A5.setText("J");
        _J_A5.setBorder(null);
        _J_A5.setFocusPainted(false);
        _J_A5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _J_A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _J_A5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_J_A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 166, 36, 215));

        _K_B5.setText("K");
        _K_B5.setBorder(null);
        _K_B5.setFocusPainted(false);
        _K_B5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _K_B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _K_B5ActionPerformed(evt);
            }
        });
        pianoPanel.add(_K_B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 166, 36, 215));

        _L_C6.setText("L");
        _L_C6.setBorder(null);
        _L_C6.setFocusPainted(false);
        _L_C6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _L_C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _L_C6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_L_C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 166, 36, 215));

        _Z_D6.setText("Z");
        _Z_D6.setBorder(null);
        _Z_D6.setFocusPainted(false);
        _Z_D6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _Z_D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _Z_D6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_Z_D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 166, 36, 215));

        _X_E6.setText("X");
        _X_E6.setBorder(null);
        _X_E6.setFocusPainted(false);
        _X_E6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _X_E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _X_E6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_X_E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 166, 36, 215));

        _C_F6.setText("C");
        _C_F6.setBorder(null);
        _C_F6.setFocusPainted(false);
        _C_F6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _C_F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _C_F6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_C_F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1069, 166, 36, 215));

        _V_G6.setText("V");
        _V_G6.setBorder(null);
        _V_G6.setFocusPainted(false);
        _V_G6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _V_G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _V_G6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_V_G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 166, 36, 215));

        _B_A6.setText("B");
        _B_A6.setBorder(null);
        _B_A6.setFocusPainted(false);
        _B_A6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _B_A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _B_A6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_B_A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 166, 36, 215));

        _N_B6.setText("N");
        _N_B6.setBorder(null);
        _N_B6.setFocusPainted(false);
        _N_B6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _N_B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _N_B6ActionPerformed(evt);
            }
        });
        pianoPanel.add(_N_B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 166, 36, 215));

        _M_C7.setText("M");
        _M_C7.setBorder(null);
        _M_C7.setFocusPainted(false);
        _M_C7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        _M_C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _M_C7ActionPerformed(evt);
            }
        });
        pianoPanel.add(_M_C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 166, 36, 215));

        keyInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        keyInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyInputActionPerformed(evt);
            }
        });
        pianoPanel.add(keyInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 460, 40));

        playTuneInput.setText("Play ");
        playTuneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playTuneInputActionPerformed(evt);
            }
        });
        pianoPanel.add(playTuneInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, -1));

        pianoBGImane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2018-06-24 00_04_24-Virtual Piano _ The Original Best Piano App Online.png"))); // NOI18N
        pianoPanel.add(pianoBGImane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        topmenu.setBackground(new java.awt.Color(0, 51, 51));
        topmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        topmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_side_menu_slider_.setBackground(new java.awt.Color(0, 51, 51));
        btn_side_menu_slider_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btn_side_menu_slider_.setBorder(null);
        btn_side_menu_slider_.setContentAreaFilled(false);
        btn_side_menu_slider_.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));
        btn_side_menu_slider_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_side_menu_slider_ActionPerformed(evt);
            }
        });
        topmenu.add(btn_side_menu_slider_, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, -1, 35));

        btn_pause_music.setBackground(new java.awt.Color(0, 153, 153));
        btn_pause_music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pause-35.png"))); // NOI18N
        btn_pause_music.setColorNormal(new java.awt.Color(0, 153, 153));
        btn_pause_music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_pause_musicMouseReleased(evt);
            }
        });
        topmenu.add(btn_pause_music, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        btn_play_music.setBackground(new java.awt.Color(0, 153, 153));
        btn_play_music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/play-35.png"))); // NOI18N
        btn_play_music.setColorNormal(new java.awt.Color(0, 153, 153));
        btn_play_music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_play_musicMouseReleased(evt);
            }
        });
        btn_play_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_play_musicActionPerformed(evt);
            }
        });
        topmenu.add(btn_play_music, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        btn_stop_record.setBackground(new java.awt.Color(0, 153, 153));
        btn_stop_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-stop-35.png"))); // NOI18N
        btn_stop_record.setColorNormal(new java.awt.Color(0, 153, 153));
        btn_stop_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stop_recordActionPerformed(evt);
            }
        });
        topmenu.add(btn_stop_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        btn_stop_music.setBackground(new java.awt.Color(0, 153, 153));
        btn_stop_music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stop-squared-filled-35.png"))); // NOI18N
        btn_stop_music.setColorNormal(new java.awt.Color(0, 153, 153));
        btn_stop_music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_stop_musicMouseReleased(evt);
            }
        });
        btn_stop_music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stop_musicActionPerformed(evt);
            }
        });
        topmenu.add(btn_stop_music, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        btn_start_record.setBackground(new java.awt.Color(0, 153, 153));
        btn_start_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-record-35.png"))); // NOI18N
        btn_start_record.setColorNormal(new java.awt.Color(0, 153, 153));
        btn_start_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start_recordActionPerformed(evt);
            }
        });
        topmenu.add(btn_start_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        lbl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        topmenu.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 470, 30));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        topmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 82, 460, 0));

        save_name_lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        topmenu.add(save_name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(topmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pianoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pianoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_play_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_play_musicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_play_musicActionPerformed

    private void btn_stop_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stop_recordActionPerformed

        save_name_lbl.setText("Saved as: "+savedFileName);
        /// stop recording
        /// stop collecting data 
        targetLine.stop();
        targetLine.close();
    }//GEN-LAST:event_btn_stop_recordActionPerformed

    private void btn_side_menu_slider_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_side_menu_slider_ActionPerformed
        int position = this.sideMenu.getX(); // get the initial X position
        if(position > -1){
            /// show slider
            Animacion.Animacion.mover_izquierda(0, -140, 2, 2, sideMenu);
        }
        else{
            /// hide slider
            Animacion.Animacion.mover_derecha(-140, 0, 2, 2, sideMenu);
        }
    }//GEN-LAST:event_btn_side_menu_slider_ActionPerformed

    private void _Y_D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Y_D4ActionPerformed
        // TODO add your handling code here:
        tone.tf_y_D4();
        
    }//GEN-LAST:event__Y_D4ActionPerformed

    private void _C_F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__C_F6ActionPerformed
        // TODO add your handling code here:
        tone.tf_c_F6();
    }//GEN-LAST:event__C_F6ActionPerformed

    private void _M_C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__M_C7ActionPerformed
        // TODO add your handling code here:
        tone.tf_m_C7();
    }//GEN-LAST:event__M_C7ActionPerformed

    private void btn_stop_musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stop_musicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_stop_musicActionPerformed

    
    ///===================== Recording ===========================///
    
    AudioFormat format; /// type of audio. we used ".wav" format.
    TargetDataLine targetLine;
    File audioFile;
    String savedFileName;
    Random rand = new Random();
    int no = rand.nextInt((1000-1)+1)-1; /// to give a random number to the recorded audio file.
    private void btn_start_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start_recordActionPerformed

      try{
            /// PCM_SIGNED is for ".wav" format
            /// 2nd paramiter is sample rete. 44100 is the highest sample rate.
            /// 3rd paramiter is sample size. we used 16 bits
            /// 4th paramiter is channel. 1 for mono. 2 for sterio.
            /// 5th paramiter is frame size.
            /// 6th paramiter is frame rate. same as sample rate.
            format = new AudioFormat(AudioFormat.Encoding.PCM_SIGNED, 44100, 16, 2, 4, 44100, false);  
            
            /// collect data from microphone by target data line.
            /// then send it to data line with audio format.
            DataLine.Info info = new DataLine.Info(TargetDataLine.class, format);
            
            /// type cast the audio data to targetDataLine.
            targetLine = (TargetDataLine)AudioSystem.getLine(info);
            
            /// selecting the starting point to start recording data.
            /// N.B: .open() dont start recording.
            targetLine.open();
            
            System.out.println("Starting Recording...");
            save_name_lbl.setText("Start's recording");
            
            /// starting recording data. 
            /// data is taken from microphone
            /// and casted to targetDataLine
            targetLine.start(); 
            
            
            Thread thread = new Thread(){
                @Override public void run(){
                    try {
                        /// get the recorded data from target line and make it audio file.
                        AudioInputStream audioStream = new AudioInputStream(targetLine);
                        
                        /// file name
                        /// save it as 
                        savedFileName = no+"record.wav";
                        audioFile = new File(savedFileName);
                        AudioSystem.write(audioStream, AudioFileFormat.Type.WAVE, audioFile);
                        System.out.println("Stopped Recording..."); /// for bug testing
                    } catch (IOException e) { System.out.println(e); }
                }
            };
            thread.start();
        } catch(Exception e) { System.out.println(e); }
    }//GEN-LAST:event_btn_start_recordActionPerformed

    /// ======================= End Recording =================================///
    private void _8_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__8_C3ActionPerformed
        // TODO add your handling code here:
        tone.tf_8_C3();
    }//GEN-LAST:event__8_C3ActionPerformed

    private void _1_C2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__1_C2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event__1_C2KeyPressed

    private void KeyPressed(java.awt.event.KeyEvent evt) {                                 
        // TODO add your handling code here:
    }
    
    private void _1_C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1_C2ActionPerformed
        // TODO add your handling code here:
        tone.tf_1_C2();
    }//GEN-LAST:event__1_C2ActionPerformed

    private void _D_D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__D_D5ActionPerformed
        // TODO add your handling code here:
        tone.tf_d_D5();
    }//GEN-LAST:event__D_D5ActionPerformed

    private void _sG_F5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sG_F5SActionPerformed
        // TODO add your handling code here:
         tone.tf_gs_F5s();
    }//GEN-LAST:event__sG_F5SActionPerformed

    private void btn_37_piano_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_37_piano_ActionPerformed
        
        /// To open the 37 piano window.
        /// Open 37 piano window, and hide main piano.
        new Frame_37().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_37_piano_ActionPerformed

    private void _2_D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2_D2ActionPerformed
        // key press 2 to play tune D2
        tone.tf_2_D2();
    }//GEN-LAST:event__2_D2ActionPerformed

    private void _3_E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3_E2ActionPerformed
        // key press 3 to play tune E2
        tone.tf_3_E2();
    }//GEN-LAST:event__3_E2ActionPerformed

    private void _4_F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4_F2ActionPerformed
        // key press 4 to play tune F2
        tone.tf_4_F2();
    }//GEN-LAST:event__4_F2ActionPerformed

    private void _5_G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5_G2ActionPerformed
        // key press 5 to play tune G2
        tone.tf_5_G2();
    }//GEN-LAST:event__5_G2ActionPerformed

    private void _6_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__6_A2ActionPerformed
        // key press 6 to play tune A2
        tone.tf_6_A2();
    }//GEN-LAST:event__6_A2ActionPerformed

    private void _7_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__7_B2ActionPerformed
        // key press 7 to play tune B2
        tone.tf_7_B2();
    }//GEN-LAST:event__7_B2ActionPerformed

    private void _9_D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__9_D3ActionPerformed
        // key press 9 to play tune D3
        tone.tf_9_D3();
    }//GEN-LAST:event__9_D3ActionPerformed

    private void _0_E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__0_E3ActionPerformed
        // key press "0" to play tune E3
        tone.tf_0_E3();
    }//GEN-LAST:event__0_E3ActionPerformed

    private void _Q_F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Q_F3ActionPerformed
        // key press "Q" to play tune F3
        tone.tf_q_F3();
    }//GEN-LAST:event__Q_F3ActionPerformed

    private void _W_G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__W_G3ActionPerformed
        // TODO add your handling code here:
        tone.tf_w_G3();
    }//GEN-LAST:event__W_G3ActionPerformed

    private void _E_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__E_A3ActionPerformed
        // TODO add your handling code here:
        tone.tf_e_A3();
    }//GEN-LAST:event__E_A3ActionPerformed

    private void _R_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__R_B3ActionPerformed
        // TODO add your handling code here:
        tone.tf_r_B3();
    }//GEN-LAST:event__R_B3ActionPerformed

    private void _T_C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__T_C4ActionPerformed
        // TODO add your handling code here:
        tone.tf_t_C4();
    }//GEN-LAST:event__T_C4ActionPerformed

    private void _U_E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__U_E4ActionPerformed
        // TODO add your handling code here:
        tone.tf_u_E4();
    }//GEN-LAST:event__U_E4ActionPerformed

    private void _I_F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__I_F4ActionPerformed
        // TODO add your handling code here:
        tone.tf_i_F4();
    }//GEN-LAST:event__I_F4ActionPerformed

    private void _O_G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__O_G4ActionPerformed
        // TODO add your handling code here:
        tone.tf_o_G4();
    }//GEN-LAST:event__O_G4ActionPerformed

    private void _P_A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__P_A4ActionPerformed
        // TODO add your handling code here:
        tone.tf_p_A4();
    }//GEN-LAST:event__P_A4ActionPerformed

    private void _A_B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__A_B4ActionPerformed
        // TODO add your handling code here:
        tone.tf_a_B4();
    }//GEN-LAST:event__A_B4ActionPerformed

    private void _S_C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__S_C5ActionPerformed
        // TODO add your handling code here:
        tone.tf_s_C5();
    }//GEN-LAST:event__S_C5ActionPerformed

    private void _F_E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__F_E5ActionPerformed
        // TODO add your handling code here:
        tone.tf_f_E5();
    }//GEN-LAST:event__F_E5ActionPerformed

    private void _G_F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__G_F5ActionPerformed
        // TODO add your handling code here:
        tone.tf_g_F5();
    }//GEN-LAST:event__G_F5ActionPerformed

    private void _H_G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__H_G5ActionPerformed
        // TODO add your handling code here:
        tone.tf_h_G5();
    }//GEN-LAST:event__H_G5ActionPerformed

    private void _J_A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__J_A5ActionPerformed
        // TODO add your handling code here:
        tone.tf_j_A5();
    }//GEN-LAST:event__J_A5ActionPerformed

    private void _K_B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__K_B5ActionPerformed
        // TODO add your handling code here:
        tone.tf_k_B5();
    }//GEN-LAST:event__K_B5ActionPerformed

    private void _L_C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__L_C6ActionPerformed
        // TODO add your handling code here:
        tone.tf_l_C6();
    }//GEN-LAST:event__L_C6ActionPerformed

    private void _Z_D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__Z_D6ActionPerformed
        // TODO add your handling code here:
        tone.tf_z_D6();
    }//GEN-LAST:event__Z_D6ActionPerformed

    private void _X_E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__X_E6ActionPerformed
        // TODO add your handling code here:
        tone.tf_x_E6();
    }//GEN-LAST:event__X_E6ActionPerformed

    private void _V_G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__V_G6ActionPerformed
        // TODO add your handling code here:
        tone.tf_v_G6();
        
    }//GEN-LAST:event__V_G6ActionPerformed

    private void _B_A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__B_A6ActionPerformed
        // TODO add your handling code here:
        tone.tf_b_A6();
    }//GEN-LAST:event__B_A6ActionPerformed

    private void _N_B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__N_B6ActionPerformed
        // TODO add your handling code here:
        tone.tf_n_B6();
    }//GEN-LAST:event__N_B6ActionPerformed

    private void _sB_A6SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sB_A6SActionPerformed
        // TODO add your handling code here:
        tone.tf_bs_A6s();
    }//GEN-LAST:event__sB_A6SActionPerformed

    private void _sV_G6SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sV_G6SActionPerformed
        // TODO add your handling code here:
         tone.tf_vs_G6s();
    }//GEN-LAST:event__sV_G6SActionPerformed

    private void _sC_F6SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sC_F6SActionPerformed
        // TODO add your handling code here:
         tone.tf_cs_F6s();
    }//GEN-LAST:event__sC_F6SActionPerformed

    private void _sZ_D6SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sZ_D6SActionPerformed
        // TODO add your handling code here:
         tone.tf_zs_D6s();
    }//GEN-LAST:event__sZ_D6SActionPerformed

    private void _sL_C6SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sL_C6SActionPerformed
        // TODO add your handling code here:
         tone.tf_ls_C6s();
    }//GEN-LAST:event__sL_C6SActionPerformed

    private void _sJ_A5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sJ_A5SActionPerformed
        // TODO add your handling code here:
         tone.tf_js_A5s();
    }//GEN-LAST:event__sJ_A5SActionPerformed

    private void _sH_G5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sH_G5SActionPerformed
        // TODO add your handling code here:
         tone.tf_hs_G5s();
    }//GEN-LAST:event__sH_G5SActionPerformed

    private void _sD_D5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sD_D5SActionPerformed
        // TODO add your handling code here:
         tone.tf_ds_D5s();
    }//GEN-LAST:event__sD_D5SActionPerformed

    private void _sS_C5SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sS_C5SActionPerformed
        // TODO add your handling code here:
         tone.tf_ss_C5s();
    }//GEN-LAST:event__sS_C5SActionPerformed

    private void _sP_A4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sP_A4SActionPerformed
        // TODO add your handling code here:
         tone.tf_ps_A4s();
    }//GEN-LAST:event__sP_A4SActionPerformed

    private void _sO_G4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sO_G4SActionPerformed
        // TODO add your handling code here:
         tone.tf_os_G4s();
    }//GEN-LAST:event__sO_G4SActionPerformed

    private void _sI_F4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sI_F4SActionPerformed
        // TODO add your handling code here:
         tone.tf_is_F4s();
    }//GEN-LAST:event__sI_F4SActionPerformed

    private void _sY_D4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sY_D4SActionPerformed
        // TODO add your handling code here:
         tone.tf_ys_D4s();
    }//GEN-LAST:event__sY_D4SActionPerformed

    private void _sT_C4SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sT_C4SActionPerformed
        // TODO add your handling code here:
         tone.tf_ts_C4s();
    }//GEN-LAST:event__sT_C4SActionPerformed

    private void _sE_A3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sE_A3SActionPerformed
        // TODO add your handling code here:
         tone.tf_es_A3s();
    }//GEN-LAST:event__sE_A3SActionPerformed

    private void _sW_G3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sW_G3SActionPerformed
        // TODO add your handling code here:
         tone.tf_ws_G3s();
    }//GEN-LAST:event__sW_G3SActionPerformed

    private void _sQ_F3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__sQ_F3SActionPerformed
        // TODO add your handling code here:
         tone.tf_qs_F3s();
    }//GEN-LAST:event__sQ_F3SActionPerformed

    private void _s9_D3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s9_D3SActionPerformed
        // TODO add your handling code here:
         tone.tf_9s_D3s();
    }//GEN-LAST:event__s9_D3SActionPerformed

    private void _s8_C3SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s8_C3SActionPerformed
        // TODO add your handling code here:
         tone.tf_8s_C3s();
    }//GEN-LAST:event__s8_C3SActionPerformed

    private void _s6_A2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s6_A2SActionPerformed
        // TODO add your handling code here:
         tone.tf_6s_A2s();
    }//GEN-LAST:event__s6_A2SActionPerformed

    private void _s5_G2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s5_G2SActionPerformed
        // TODO add your handling code here:
         tone.tf_5s_G2s();
    }//GEN-LAST:event__s5_G2SActionPerformed

    private void _s4_F2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s4_F2SActionPerformed
        // TODO add your handling code here:
         tone.tf_4s_F2s();
    }//GEN-LAST:event__s4_F2SActionPerformed

    private void _s2_D2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s2_D2SActionPerformed
        // TODO add your handling code here:
         tone.tf_2s_D2s();
    }//GEN-LAST:event__s2_D2SActionPerformed

    private void _s1_C2SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__s1_C2SActionPerformed
        // TODO add your handling code here:
         tone.tf_1s_C2s();
    }//GEN-LAST:event__s1_C2SActionPerformed

    
    /// =========================== Play Music ==================================///
    boolean playing = false;
    boolean poused = true;
    long total_length;
    long pouse;
    FileInputStream FIS;
    BufferedInputStream BIS;
    Player player;
    File myFile = null;
    
    private void btn_play_musicMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_play_musicMouseReleased
        
            /// open file chooser
        JFileChooser chooser = new JFileChooser();
        int val = chooser.showOpenDialog(null);

        
        if (val == JFileChooser.APPROVE_OPTION) {
            myFile = chooser.getSelectedFile(); // select a mp3 file.
            String song = myFile + ""; // convert file name to string
            String name = chooser.getSelectedFile().getName();
            lbl.setText(name); // display mp3 name to lable
        }
        try {
            FIS = new FileInputStream(myFile); // choosing the target file
            BIS = new BufferedInputStream(FIS); // buffer data to play 
            player = new Player(BIS); 
            total_length = FIS.available(); // total length of the song i.e mp3 data. 

            new Thread() {
                public void run() {
                    try {
                        player.play(); // play mp3 using buffer data
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }.start();
        } catch (Exception e) {
            System.out.println(e);
        }
        poused = true;
        playing = false; 
    }//GEN-LAST:event_btn_play_musicMouseReleased

    private void btn_pause_musicMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pause_musicMouseReleased
        if (player != null) {
            try {
                pouse = FIS.available(); // mp3 will pouse if it is playing
                player.close(); // stop, if the data i.e song is end.
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btn_pause_musicMouseReleased

    private void btn_stop_musicMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stop_musicMouseReleased
        if (player != null) { // check if music is playing or not
            player.close(); // stop the music
            lbl.setText(null);
        }
    }//GEN-LAST:event_btn_stop_musicMouseReleased

    /// =============================== End Music ========================================///
    
    private void keyInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyInputActionPerformed

    private void btn_equalizer_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equalizer_ActionPerformed
        // TODO add your handling code here:
        new Equalizer().setVisible(true);
    }//GEN-LAST:event_btn_equalizer_ActionPerformed
    
    String temp;
    static int delay = 300;
    public int getDelay() {
        return delay;
    }

    public static void setDelay(int delay) {
        MyFrame.delay = delay;
    }

    public RSButtonMetro getrSButtonMetro8() {
        return btn_37_piano_;
    }

    public void setrSButtonMetro8(RSButtonMetro rSButtonMetro8) {
        this.btn_37_piano_ = rSButtonMetro8;
    }
    
    /// ========================== AutoPlay ==================================== ///
    
    private void playTuneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playTuneInputActionPerformed
        // TODO add your handling code here:
        temp = keyInput.getText();
        System.out.println(temp);
        int len = temp.length();
        for (int i = 0; i < len; i++) {
            
                char check = temp.charAt(i);
                if(check == 'y'){
                    tone.tf_y_D4();
                }
                if(check == 'p'){
                    tone.tf_p_A4();
                }
                if(check == 'u'){
                    tone.tf_u_E4();
                }
                if(check == 'i'){
                    tone.tf_i_F4();
                }
                if(check == '1'){
                    tone.tf_1_C2();
                }
                if(check == '2'){
                    tone.tf_2_D2();
                }
                if(check == '3'){
                    tone.tf_3_E2();
                }
                if(check == '4'){
                    tone.tf_4_F2();
                }
                if(check == '5'){
                    tone.tf_5_G2();
                }
                if(check == '6'){
                    tone.tf_6_A2();
                }
                if(check == '7'){
                    tone.tf_7_B2();
                }
                if(check == '8'){
                    tone.tf_8_C3();
                }
                if(check == '9'){
                    tone.tf_9_D3();
                }
                if(check == '0'){
                    tone.tf_0_E3();
                }
                if(check == 'q'){
                    tone.tf_q_F3();
                }
                if(check == 'w'){
                   tone.tf_w_G3();
                }
                if(check == 'e'){
                    tone.tf_e_A3();
                }
                if(check == 'r'){
                    tone.tf_r_B3();
                }
                if(check == 't'){
                    tone.tf_t_C4();
                }
                if(check == 'o'){
                    tone.tf_o_G4();
                }
                if(check == 'a'){
                    tone.tf_a_B4();
                }
                if(check == 's'){
                    tone.tf_s_C5();
                }
                if(check == 'd'){
                    tone.tf_d_D5();
                }
                if(check == 'f'){
                    tone.tf_f_E5();
                }
                if(check == 'g'){
                    tone.tf_g_F5();
                }
                if(check == 'h'){
                    tone.tf_h_G5();
                }
                if(check == 'j'){
                    tone.tf_j_A5();
                }
                if(check == 'k'){
                    tone.tf_k_B5();
                }
                if(check == 'l'){
                    tone.tf_l_C6();
                }
                if(check == 'z'){
                    tone.tf_z_D6();
                }
                if(check == 'x'){
                    tone.tf_x_E6();
                }
                if(check == 'c'){
                    tone.tf_c_F6();
                }
                if(check == 'v'){
                    tone.tf_v_G6();
                }
                if(check == 'b'){
                    tone.tf_b_A6();
                }
                if(check == 'n'){
                    tone.tf_n_B6();
                }
                if(check == 'm'){
                    tone.tf_m_C7();
                }
                if(check == ' '){
                    // tone function
                }
                if(check == ' '){
                    // tone function
                }
        
                 
                if(check == ' '){
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                
            try {
                Thread.sleep(delay);
            } catch (InterruptedException ex) {
                Logger.getLogger(MyFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_playTuneInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _0_E3;
    private javax.swing.JButton _1_C2;
    private javax.swing.JButton _2_D2;
    private javax.swing.JButton _3_E2;
    private javax.swing.JButton _4_F2;
    private javax.swing.JButton _5_G2;
    private javax.swing.JButton _6_A2;
    private javax.swing.JButton _7_B2;
    private javax.swing.JButton _8_C3;
    private javax.swing.JButton _9_D3;
    private javax.swing.JButton _A_B4;
    private javax.swing.JButton _B_A6;
    private javax.swing.JButton _C_F6;
    private javax.swing.JButton _D_D5;
    private javax.swing.JButton _E_A3;
    private javax.swing.JButton _F_E5;
    private javax.swing.JButton _G_F5;
    private javax.swing.JButton _H_G5;
    private javax.swing.JButton _I_F4;
    private javax.swing.JButton _J_A5;
    private javax.swing.JButton _K_B5;
    private javax.swing.JButton _L_C6;
    private javax.swing.JButton _M_C7;
    private javax.swing.JButton _N_B6;
    private javax.swing.JButton _O_G4;
    private javax.swing.JButton _P_A4;
    private javax.swing.JButton _Q_F3;
    private javax.swing.JButton _R_B3;
    private javax.swing.JButton _S_C5;
    private javax.swing.JButton _T_C4;
    private javax.swing.JButton _U_E4;
    private javax.swing.JButton _V_G6;
    private javax.swing.JButton _W_G3;
    private javax.swing.JButton _X_E6;
    private javax.swing.JButton _Y_D4;
    private javax.swing.JButton _Z_D6;
    private javax.swing.JButton _s1_C2S;
    private javax.swing.JButton _s2_D2S;
    private javax.swing.JButton _s4_F2S;
    private javax.swing.JButton _s5_G2S;
    private javax.swing.JButton _s6_A2S;
    private javax.swing.JButton _s8_C3S;
    private javax.swing.JButton _s9_D3S;
    private javax.swing.JButton _sB_A6S;
    private javax.swing.JButton _sC_F6S;
    private javax.swing.JButton _sD_D5S;
    private javax.swing.JButton _sE_A3S;
    private javax.swing.JButton _sG_F5S;
    private javax.swing.JButton _sH_G5S;
    private javax.swing.JButton _sI_F4S;
    private javax.swing.JButton _sJ_A5S;
    private javax.swing.JButton _sL_C6S;
    private javax.swing.JButton _sO_G4S;
    private javax.swing.JButton _sP_A4S;
    private javax.swing.JButton _sQ_F3S;
    private javax.swing.JButton _sS_C5S;
    private javax.swing.JButton _sT_C4S;
    private javax.swing.JButton _sV_G6S;
    private javax.swing.JButton _sW_G3S;
    private javax.swing.JButton _sY_D4S;
    private javax.swing.JButton _sZ_D6S;
    private rsbutton.RSButtonMetro btn_37_piano_;
    private rsbutton.RSButtonMetro btn_61_piano_;
    private rsbutton.RSButtonMetro btn_equalizer_;
    private rsbutton.RSButtonMetro btn_pause_music;
    private rsbutton.RSButtonMetro btn_play_music;
    private javax.swing.JButton btn_side_menu_slider_;
    private rsbutton.RSButtonMetro btn_start_record;
    private rsbutton.RSButtonMetro btn_stop_music;
    private rsbutton.RSButtonMetro btn_stop_record;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField keyInput;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel pianoBGImane;
    private javax.swing.JPanel pianoPanel;
    private rsbutton.RSButtonMetro playTuneInput;
    private javax.swing.JLabel save_name_lbl;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JPanel topmenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) { }

    @Override
    public void keyPressed(KeyEvent e) {

        ///======================= chat input ================================///
        if(e.getKeyChar() == '1'){
            tone.tf_1_C2();
        }
        if(e.getKeyChar() == '2'){
            tone.tf_2_D2();
        }
        if(e.getKeyChar() == '3'){
            tone.tf_3_E2();
        }
        if(e.getKeyChar() == '4'){
            tone.tf_4_F2();
        }
        if(e.getKeyChar() == '5'){
            tone.tf_5_G2();
        }
        if(e.getKeyChar() == '6'){
            tone.tf_6_A2();
        }
        if(e.getKeyChar() == '7'){
            tone.tf_7_B2();
        }
        if(e.getKeyChar() == '8'){
            tone.tf_8_C3();
        }
        if(e.getKeyChar() == '9'){
            tone.tf_9_D3();
        }
        if(e.getKeyChar() == '0'){
            tone.tf_0_E3();
        }
        if(e.getKeyChar() == 'q'){
            tone.tf_q_F3();
        }
        if(e.getKeyChar() == 'w'){
            tone.tf_w_G3();
        }
        if(e.getKeyChar() == 'e'){
            tone.tf_e_A3();
        }
        if(e.getKeyChar() == 'r'){
            tone.tf_r_B3();
        }
        if(e.getKeyChar() == 't'){
            tone.tf_t_C4();
        }
        if(e.getKeyChar() == 'y'){
            tone.tf_y_D4();
        }
        if(e.getKeyChar() == 'u'){
            tone.tf_u_E4();
        }
        if(e.getKeyChar() == 'i'){
            tone.tf_i_F4();
        }
        if(e.getKeyChar() == 'o'){
            tone.tf_o_G4();
        }
        if(e.getKeyChar() == 'p'){
            tone.tf_p_A4();
        }
        if(e.getKeyChar() == 'a'){
            tone.tf_a_B4();
        }
        if(e.getKeyChar() == 's'){
            tone.tf_s_C5();
        }
        if(e.getKeyChar() == 'd'){
            tone.tf_d_D5();
        }
        if(e.getKeyChar() == 'f'){
            tone.tf_f_E5();
        }
        if(e.getKeyChar() == 'g'){
            tone.tf_g_F5();
        }
        if(e.getKeyChar() == 'h'){
            tone.tf_h_G5();
        }
        if(e.getKeyChar() == 'j'){
            tone.tf_j_A5();
        }
        if(e.getKeyChar() == 'k'){
            tone.tf_k_B5();
        }
        if(e.getKeyChar() == 'l'){
            tone.tf_l_C6();
        }
        if(e.getKeyChar() == 'z'){
            tone.tf_z_D6();
        }
        if(e.getKeyChar() == 'x'){
            tone.tf_x_E6();
        }
        if(e.getKeyChar() == 'c'){
            tone.tf_c_F6();
        }
        if(e.getKeyChar() == 'v'){
            tone.tf_v_G6();
        }
        if(e.getKeyChar() == 'b'){
            tone.tf_b_A6();
        }
        if(e.getKeyChar() == 'n'){
            tone.tf_n_B6();
        }
        if(e.getKeyChar() == 'm'){
            tone.tf_m_C7();
        }
        
        
        ///// Sharps
        if(e.getKeyChar() == '!'){
            tone.tf_1s_C2s();
        }
        if(e.getKeyChar() == '@'){
            tone.tf_2s_D2s();
        }
        if(e.getKeyChar() == '$'){
            tone.tf_4s_F2s();
        }
        if(e.getKeyChar() == '%'){
            tone.tf_5s_G2s();
        }
        if(e.getKeyChar() == '^'){
            tone.tf_6s_A2s();
        }
        if(e.getKeyChar() == '*'){
            tone.tf_8s_C3s();
        }
        if(e.getKeyChar() == '('){
            tone.tf_9s_D3s();
        }
        if(e.getKeyChar() == 'Q'){
            tone.tf_qs_F3s();
        }
        if(e.getKeyChar() == 'W'){
            tone.tf_ws_G3s();
        }
        if(e.getKeyChar() == 'E'){
            tone.tf_es_A3s();
        }
        if(e.getKeyChar() == 'T'){
            tone.tf_ts_C4s();
        }
        if(e.getKeyChar() == 'Y'){
            tone.tf_ys_D4s();
        }
        if(e.getKeyChar() == 'I'){
            tone.tf_is_F4s();
        }
        if(e.getKeyChar() == 'O'){
            tone.tf_os_G4s();
        }
        if(e.getKeyChar() == 'P'){
            tone.tf_ps_A4s();
        }
        if(e.getKeyChar() == 'S'){
            tone.tf_ss_C5s();
        }
        if(e.getKeyChar() == 'D'){
            tone.tf_ds_D5s();
        }
        if(e.getKeyChar() == 'G'){
            tone.tf_gs_F5s();
        }
        if(e.getKeyChar() == 'H'){
            tone.tf_hs_G5s();
        }
        if(e.getKeyChar() == 'J'){
            tone.tf_js_A5s();
        }
        if(e.getKeyChar() == 'L'){
            tone.tf_ls_C6s();
        }
        if(e.getKeyChar() == 'Z'){
            tone.tf_zs_D6s();
        }
        if(e.getKeyChar() == 'C'){
            tone.tf_cs_F6s();
        }
        if(e.getKeyChar() == 'V'){
            tone.tf_vs_G6s();
        }
        if(e.getKeyChar() == 'B'){
            tone.tf_bs_A6s();
        }
        
        
        ///========================= end char input ===================================///
        
        

    }

    @Override
    public void keyReleased(KeyEvent e) { }
}
